CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_MAIN_STACK_SIZE=1024

CONFIG_APP_RING_BUFFER_CAPACITY=20
CONFIG_APP_PRODUCER_PERIOD_SECONDS=1
CONFIG_APP_CONSUMER_PERIOD_SECONDS=10
CONFIG_APP_THREAD_STACK_SIZE=1024
CONFIG_APP_THREAD_PRIORITY=5